// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (m *Meshi) Municipality(ctx context.Context) (*Municipality, error) {
	result, err := m.Edges.MunicipalityOrErr()
	if IsNotLoaded(err) {
		result, err = m.QueryMunicipality().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (m *Municipality) Meshis(ctx context.Context) (result []*Meshi, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = m.NamedMeshis(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = m.Edges.MeshisOrErr()
	}
	if IsNotLoaded(err) {
		result, err = m.QueryMeshis().All(ctx)
	}
	return result, err
}
