// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shimabukuromeg/ageage-search/ent/meshi"
	"github.com/shimabukuromeg/ageage-search/ent/municipality"
	"github.com/shimabukuromeg/ageage-search/ent/predicate"
)

// MeshiQuery is the builder for querying Meshi entities.
type MeshiQuery struct {
	config
	ctx              *QueryContext
	order            []meshi.OrderOption
	inters           []Interceptor
	predicates       []predicate.Meshi
	withMunicipality *MunicipalityQuery
	withFKs          bool
	modifiers        []func(*sql.Selector)
	loadTotal        []func(context.Context, []*Meshi) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MeshiQuery builder.
func (mq *MeshiQuery) Where(ps ...predicate.Meshi) *MeshiQuery {
	mq.predicates = append(mq.predicates, ps...)
	return mq
}

// Limit the number of records to be returned by this query.
func (mq *MeshiQuery) Limit(limit int) *MeshiQuery {
	mq.ctx.Limit = &limit
	return mq
}

// Offset to start from.
func (mq *MeshiQuery) Offset(offset int) *MeshiQuery {
	mq.ctx.Offset = &offset
	return mq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mq *MeshiQuery) Unique(unique bool) *MeshiQuery {
	mq.ctx.Unique = &unique
	return mq
}

// Order specifies how the records should be ordered.
func (mq *MeshiQuery) Order(o ...meshi.OrderOption) *MeshiQuery {
	mq.order = append(mq.order, o...)
	return mq
}

// QueryMunicipality chains the current query on the "municipality" edge.
func (mq *MeshiQuery) QueryMunicipality() *MunicipalityQuery {
	query := (&MunicipalityClient{config: mq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(meshi.Table, meshi.FieldID, selector),
			sqlgraph.To(municipality.Table, municipality.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, meshi.MunicipalityTable, meshi.MunicipalityColumn),
		)
		fromU = sqlgraph.SetNeighbors(mq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Meshi entity from the query.
// Returns a *NotFoundError when no Meshi was found.
func (mq *MeshiQuery) First(ctx context.Context) (*Meshi, error) {
	nodes, err := mq.Limit(1).All(setContextOp(ctx, mq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{meshi.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mq *MeshiQuery) FirstX(ctx context.Context) *Meshi {
	node, err := mq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Meshi ID from the query.
// Returns a *NotFoundError when no Meshi ID was found.
func (mq *MeshiQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(1).IDs(setContextOp(ctx, mq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{meshi.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mq *MeshiQuery) FirstIDX(ctx context.Context) int {
	id, err := mq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Meshi entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Meshi entity is found.
// Returns a *NotFoundError when no Meshi entities are found.
func (mq *MeshiQuery) Only(ctx context.Context) (*Meshi, error) {
	nodes, err := mq.Limit(2).All(setContextOp(ctx, mq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{meshi.Label}
	default:
		return nil, &NotSingularError{meshi.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mq *MeshiQuery) OnlyX(ctx context.Context) *Meshi {
	node, err := mq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Meshi ID in the query.
// Returns a *NotSingularError when more than one Meshi ID is found.
// Returns a *NotFoundError when no entities are found.
func (mq *MeshiQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mq.Limit(2).IDs(setContextOp(ctx, mq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{meshi.Label}
	default:
		err = &NotSingularError{meshi.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mq *MeshiQuery) OnlyIDX(ctx context.Context) int {
	id, err := mq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Meshis.
func (mq *MeshiQuery) All(ctx context.Context) ([]*Meshi, error) {
	ctx = setContextOp(ctx, mq.ctx, "All")
	if err := mq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Meshi, *MeshiQuery]()
	return withInterceptors[[]*Meshi](ctx, mq, qr, mq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mq *MeshiQuery) AllX(ctx context.Context) []*Meshi {
	nodes, err := mq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Meshi IDs.
func (mq *MeshiQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mq.ctx.Unique == nil && mq.path != nil {
		mq.Unique(true)
	}
	ctx = setContextOp(ctx, mq.ctx, "IDs")
	if err = mq.Select(meshi.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mq *MeshiQuery) IDsX(ctx context.Context) []int {
	ids, err := mq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mq *MeshiQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mq.ctx, "Count")
	if err := mq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mq, querierCount[*MeshiQuery](), mq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mq *MeshiQuery) CountX(ctx context.Context) int {
	count, err := mq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mq *MeshiQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mq.ctx, "Exist")
	switch _, err := mq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mq *MeshiQuery) ExistX(ctx context.Context) bool {
	exist, err := mq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MeshiQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mq *MeshiQuery) Clone() *MeshiQuery {
	if mq == nil {
		return nil
	}
	return &MeshiQuery{
		config:           mq.config,
		ctx:              mq.ctx.Clone(),
		order:            append([]meshi.OrderOption{}, mq.order...),
		inters:           append([]Interceptor{}, mq.inters...),
		predicates:       append([]predicate.Meshi{}, mq.predicates...),
		withMunicipality: mq.withMunicipality.Clone(),
		// clone intermediate query.
		sql:  mq.sql.Clone(),
		path: mq.path,
	}
}

// WithMunicipality tells the query-builder to eager-load the nodes that are connected to
// the "municipality" edge. The optional arguments are used to configure the query builder of the edge.
func (mq *MeshiQuery) WithMunicipality(opts ...func(*MunicipalityQuery)) *MeshiQuery {
	query := (&MunicipalityClient{config: mq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mq.withMunicipality = query
	return mq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ArticleID string `json:"article_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Meshi.Query().
//		GroupBy(meshi.FieldArticleID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mq *MeshiQuery) GroupBy(field string, fields ...string) *MeshiGroupBy {
	mq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MeshiGroupBy{build: mq}
	grbuild.flds = &mq.ctx.Fields
	grbuild.label = meshi.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ArticleID string `json:"article_id,omitempty"`
//	}
//
//	client.Meshi.Query().
//		Select(meshi.FieldArticleID).
//		Scan(ctx, &v)
func (mq *MeshiQuery) Select(fields ...string) *MeshiSelect {
	mq.ctx.Fields = append(mq.ctx.Fields, fields...)
	sbuild := &MeshiSelect{MeshiQuery: mq}
	sbuild.label = meshi.Label
	sbuild.flds, sbuild.scan = &mq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MeshiSelect configured with the given aggregations.
func (mq *MeshiQuery) Aggregate(fns ...AggregateFunc) *MeshiSelect {
	return mq.Select().Aggregate(fns...)
}

func (mq *MeshiQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mq); err != nil {
				return err
			}
		}
	}
	for _, f := range mq.ctx.Fields {
		if !meshi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mq.path != nil {
		prev, err := mq.path(ctx)
		if err != nil {
			return err
		}
		mq.sql = prev
	}
	return nil
}

func (mq *MeshiQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Meshi, error) {
	var (
		nodes       = []*Meshi{}
		withFKs     = mq.withFKs
		_spec       = mq.querySpec()
		loadedTypes = [1]bool{
			mq.withMunicipality != nil,
		}
	)
	if mq.withMunicipality != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, meshi.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Meshi).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Meshi{config: mq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(mq.modifiers) > 0 {
		_spec.Modifiers = mq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mq.withMunicipality; query != nil {
		if err := mq.loadMunicipality(ctx, query, nodes, nil,
			func(n *Meshi, e *Municipality) { n.Edges.Municipality = e }); err != nil {
			return nil, err
		}
	}
	for i := range mq.loadTotal {
		if err := mq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mq *MeshiQuery) loadMunicipality(ctx context.Context, query *MunicipalityQuery, nodes []*Meshi, init func(*Meshi), assign func(*Meshi, *Municipality)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Meshi)
	for i := range nodes {
		if nodes[i].municipality_meshis == nil {
			continue
		}
		fk := *nodes[i].municipality_meshis
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(municipality.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "municipality_meshis" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mq *MeshiQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mq.querySpec()
	if len(mq.modifiers) > 0 {
		_spec.Modifiers = mq.modifiers
	}
	_spec.Node.Columns = mq.ctx.Fields
	if len(mq.ctx.Fields) > 0 {
		_spec.Unique = mq.ctx.Unique != nil && *mq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mq.driver, _spec)
}

func (mq *MeshiQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(meshi.Table, meshi.Columns, sqlgraph.NewFieldSpec(meshi.FieldID, field.TypeInt))
	_spec.From = mq.sql
	if unique := mq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mq.path != nil {
		_spec.Unique = true
	}
	if fields := mq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, meshi.FieldID)
		for i := range fields {
			if fields[i] != meshi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mq *MeshiQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mq.driver.Dialect())
	t1 := builder.Table(meshi.Table)
	columns := mq.ctx.Fields
	if len(columns) == 0 {
		columns = meshi.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mq.sql != nil {
		selector = mq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mq.ctx.Unique != nil && *mq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mq.predicates {
		p(selector)
	}
	for _, p := range mq.order {
		p(selector)
	}
	if offset := mq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MeshiGroupBy is the group-by builder for Meshi entities.
type MeshiGroupBy struct {
	selector
	build *MeshiQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mgb *MeshiGroupBy) Aggregate(fns ...AggregateFunc) *MeshiGroupBy {
	mgb.fns = append(mgb.fns, fns...)
	return mgb
}

// Scan applies the selector query and scans the result into the given value.
func (mgb *MeshiGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mgb.build.ctx, "GroupBy")
	if err := mgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshiQuery, *MeshiGroupBy](ctx, mgb.build, mgb, mgb.build.inters, v)
}

func (mgb *MeshiGroupBy) sqlScan(ctx context.Context, root *MeshiQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mgb.fns))
	for _, fn := range mgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mgb.flds)+len(mgb.fns))
		for _, f := range *mgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MeshiSelect is the builder for selecting fields of Meshi entities.
type MeshiSelect struct {
	*MeshiQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ms *MeshiSelect) Aggregate(fns ...AggregateFunc) *MeshiSelect {
	ms.fns = append(ms.fns, fns...)
	return ms
}

// Scan applies the selector query and scans the result into the given value.
func (ms *MeshiSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ms.ctx, "Select")
	if err := ms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MeshiQuery, *MeshiSelect](ctx, ms.MeshiQuery, ms, ms.inters, v)
}

func (ms *MeshiSelect) sqlScan(ctx context.Context, root *MeshiQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ms.fns))
	for _, fn := range ms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
