// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shimabukuromeg/ageage-search/ent/meshi"
	"github.com/shimabukuromeg/ageage-search/ent/municipality"
)

// MeshiCreate is the builder for creating a Meshi entity.
type MeshiCreate struct {
	config
	mutation *MeshiMutation
	hooks    []Hook
}

// SetArticleID sets the "article_id" field.
func (mc *MeshiCreate) SetArticleID(s string) *MeshiCreate {
	mc.mutation.SetArticleID(s)
	return mc
}

// SetTitle sets the "title" field.
func (mc *MeshiCreate) SetTitle(s string) *MeshiCreate {
	mc.mutation.SetTitle(s)
	return mc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (mc *MeshiCreate) SetNillableTitle(s *string) *MeshiCreate {
	if s != nil {
		mc.SetTitle(*s)
	}
	return mc
}

// SetImageURL sets the "image_url" field.
func (mc *MeshiCreate) SetImageURL(s string) *MeshiCreate {
	mc.mutation.SetImageURL(s)
	return mc
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (mc *MeshiCreate) SetNillableImageURL(s *string) *MeshiCreate {
	if s != nil {
		mc.SetImageURL(*s)
	}
	return mc
}

// SetStoreName sets the "store_name" field.
func (mc *MeshiCreate) SetStoreName(s string) *MeshiCreate {
	mc.mutation.SetStoreName(s)
	return mc
}

// SetNillableStoreName sets the "store_name" field if the given value is not nil.
func (mc *MeshiCreate) SetNillableStoreName(s *string) *MeshiCreate {
	if s != nil {
		mc.SetStoreName(*s)
	}
	return mc
}

// SetAddress sets the "address" field.
func (mc *MeshiCreate) SetAddress(s string) *MeshiCreate {
	mc.mutation.SetAddress(s)
	return mc
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (mc *MeshiCreate) SetNillableAddress(s *string) *MeshiCreate {
	if s != nil {
		mc.SetAddress(*s)
	}
	return mc
}

// SetSiteURL sets the "site_url" field.
func (mc *MeshiCreate) SetSiteURL(s string) *MeshiCreate {
	mc.mutation.SetSiteURL(s)
	return mc
}

// SetNillableSiteURL sets the "site_url" field if the given value is not nil.
func (mc *MeshiCreate) SetNillableSiteURL(s *string) *MeshiCreate {
	if s != nil {
		mc.SetSiteURL(*s)
	}
	return mc
}

// SetPublishedDate sets the "published_date" field.
func (mc *MeshiCreate) SetPublishedDate(t time.Time) *MeshiCreate {
	mc.mutation.SetPublishedDate(t)
	return mc
}

// SetLatitude sets the "latitude" field.
func (mc *MeshiCreate) SetLatitude(f float64) *MeshiCreate {
	mc.mutation.SetLatitude(f)
	return mc
}

// SetLongitude sets the "longitude" field.
func (mc *MeshiCreate) SetLongitude(f float64) *MeshiCreate {
	mc.mutation.SetLongitude(f)
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MeshiCreate) SetCreatedAt(t time.Time) *MeshiCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MeshiCreate) SetNillableCreatedAt(t *time.Time) *MeshiCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetMunicipalityID sets the "municipality" edge to the Municipality entity by ID.
func (mc *MeshiCreate) SetMunicipalityID(id int) *MeshiCreate {
	mc.mutation.SetMunicipalityID(id)
	return mc
}

// SetNillableMunicipalityID sets the "municipality" edge to the Municipality entity by ID if the given value is not nil.
func (mc *MeshiCreate) SetNillableMunicipalityID(id *int) *MeshiCreate {
	if id != nil {
		mc = mc.SetMunicipalityID(*id)
	}
	return mc
}

// SetMunicipality sets the "municipality" edge to the Municipality entity.
func (mc *MeshiCreate) SetMunicipality(m *Municipality) *MeshiCreate {
	return mc.SetMunicipalityID(m.ID)
}

// Mutation returns the MeshiMutation object of the builder.
func (mc *MeshiCreate) Mutation() *MeshiMutation {
	return mc.mutation
}

// Save creates the Meshi in the database.
func (mc *MeshiCreate) Save(ctx context.Context) (*Meshi, error) {
	mc.defaults()
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MeshiCreate) SaveX(ctx context.Context) *Meshi {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MeshiCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MeshiCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MeshiCreate) defaults() {
	if _, ok := mc.mutation.Title(); !ok {
		v := meshi.DefaultTitle
		mc.mutation.SetTitle(v)
	}
	if _, ok := mc.mutation.ImageURL(); !ok {
		v := meshi.DefaultImageURL
		mc.mutation.SetImageURL(v)
	}
	if _, ok := mc.mutation.StoreName(); !ok {
		v := meshi.DefaultStoreName
		mc.mutation.SetStoreName(v)
	}
	if _, ok := mc.mutation.Address(); !ok {
		v := meshi.DefaultAddress
		mc.mutation.SetAddress(v)
	}
	if _, ok := mc.mutation.SiteURL(); !ok {
		v := meshi.DefaultSiteURL
		mc.mutation.SetSiteURL(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := meshi.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MeshiCreate) check() error {
	if _, ok := mc.mutation.ArticleID(); !ok {
		return &ValidationError{Name: "article_id", err: errors.New(`ent: missing required field "Meshi.article_id"`)}
	}
	if _, ok := mc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Meshi.title"`)}
	}
	if _, ok := mc.mutation.ImageURL(); !ok {
		return &ValidationError{Name: "image_url", err: errors.New(`ent: missing required field "Meshi.image_url"`)}
	}
	if _, ok := mc.mutation.StoreName(); !ok {
		return &ValidationError{Name: "store_name", err: errors.New(`ent: missing required field "Meshi.store_name"`)}
	}
	if _, ok := mc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Meshi.address"`)}
	}
	if _, ok := mc.mutation.SiteURL(); !ok {
		return &ValidationError{Name: "site_url", err: errors.New(`ent: missing required field "Meshi.site_url"`)}
	}
	if _, ok := mc.mutation.PublishedDate(); !ok {
		return &ValidationError{Name: "published_date", err: errors.New(`ent: missing required field "Meshi.published_date"`)}
	}
	if _, ok := mc.mutation.Latitude(); !ok {
		return &ValidationError{Name: "latitude", err: errors.New(`ent: missing required field "Meshi.latitude"`)}
	}
	if _, ok := mc.mutation.Longitude(); !ok {
		return &ValidationError{Name: "longitude", err: errors.New(`ent: missing required field "Meshi.longitude"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Meshi.created_at"`)}
	}
	return nil
}

func (mc *MeshiCreate) sqlSave(ctx context.Context) (*Meshi, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MeshiCreate) createSpec() (*Meshi, *sqlgraph.CreateSpec) {
	var (
		_node = &Meshi{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(meshi.Table, sqlgraph.NewFieldSpec(meshi.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.ArticleID(); ok {
		_spec.SetField(meshi.FieldArticleID, field.TypeString, value)
		_node.ArticleID = value
	}
	if value, ok := mc.mutation.Title(); ok {
		_spec.SetField(meshi.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := mc.mutation.ImageURL(); ok {
		_spec.SetField(meshi.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if value, ok := mc.mutation.StoreName(); ok {
		_spec.SetField(meshi.FieldStoreName, field.TypeString, value)
		_node.StoreName = value
	}
	if value, ok := mc.mutation.Address(); ok {
		_spec.SetField(meshi.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := mc.mutation.SiteURL(); ok {
		_spec.SetField(meshi.FieldSiteURL, field.TypeString, value)
		_node.SiteURL = value
	}
	if value, ok := mc.mutation.PublishedDate(); ok {
		_spec.SetField(meshi.FieldPublishedDate, field.TypeTime, value)
		_node.PublishedDate = value
	}
	if value, ok := mc.mutation.Latitude(); ok {
		_spec.SetField(meshi.FieldLatitude, field.TypeFloat64, value)
		_node.Latitude = value
	}
	if value, ok := mc.mutation.Longitude(); ok {
		_spec.SetField(meshi.FieldLongitude, field.TypeFloat64, value)
		_node.Longitude = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(meshi.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := mc.mutation.MunicipalityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   meshi.MunicipalityTable,
			Columns: []string{meshi.MunicipalityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(municipality.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.municipality_meshis = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MeshiCreateBulk is the builder for creating many Meshi entities in bulk.
type MeshiCreateBulk struct {
	config
	err      error
	builders []*MeshiCreate
}

// Save creates the Meshi entities in the database.
func (mcb *MeshiCreateBulk) Save(ctx context.Context) ([]*Meshi, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Meshi, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MeshiMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MeshiCreateBulk) SaveX(ctx context.Context) []*Meshi {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MeshiCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MeshiCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
