// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/shimabukuromeg/ageage-search/ent/meshi"
	"github.com/shimabukuromeg/ageage-search/ent/municipality"
	"github.com/shimabukuromeg/ageage-search/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	meshiFields := schema.Meshi{}.Fields()
	_ = meshiFields
	// meshiDescTitle is the schema descriptor for title field.
	meshiDescTitle := meshiFields[1].Descriptor()
	// meshi.DefaultTitle holds the default value on creation for the title field.
	meshi.DefaultTitle = meshiDescTitle.Default.(string)
	// meshiDescImageURL is the schema descriptor for image_url field.
	meshiDescImageURL := meshiFields[2].Descriptor()
	// meshi.DefaultImageURL holds the default value on creation for the image_url field.
	meshi.DefaultImageURL = meshiDescImageURL.Default.(string)
	// meshiDescStoreName is the schema descriptor for store_name field.
	meshiDescStoreName := meshiFields[3].Descriptor()
	// meshi.DefaultStoreName holds the default value on creation for the store_name field.
	meshi.DefaultStoreName = meshiDescStoreName.Default.(string)
	// meshiDescAddress is the schema descriptor for address field.
	meshiDescAddress := meshiFields[4].Descriptor()
	// meshi.DefaultAddress holds the default value on creation for the address field.
	meshi.DefaultAddress = meshiDescAddress.Default.(string)
	// meshiDescSiteURL is the schema descriptor for site_url field.
	meshiDescSiteURL := meshiFields[5].Descriptor()
	// meshi.DefaultSiteURL holds the default value on creation for the site_url field.
	meshi.DefaultSiteURL = meshiDescSiteURL.Default.(string)
	// meshiDescCreatedAt is the schema descriptor for created_at field.
	meshiDescCreatedAt := meshiFields[9].Descriptor()
	// meshi.DefaultCreatedAt holds the default value on creation for the created_at field.
	meshi.DefaultCreatedAt = meshiDescCreatedAt.Default.(func() time.Time)
	municipalityFields := schema.Municipality{}.Fields()
	_ = municipalityFields
	// municipalityDescCreatedAt is the schema descriptor for created_at field.
	municipalityDescCreatedAt := municipalityFields[1].Descriptor()
	// municipality.DefaultCreatedAt holds the default value on creation for the created_at field.
	municipality.DefaultCreatedAt = municipalityDescCreatedAt.Default.(func() time.Time)
}
