// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Meshi is the predicate function for meshi builders.
type Meshi func(*sql.Selector)

// Municipality is the predicate function for municipality builders.
type Municipality func(*sql.Selector)
